import {
  FiLogOut,
  FiMenu,
  FiSettings,
  FiHelpCircle,
  FiUser,
  FiCheck,
  FiMessageSquare,
  FiChevronLeft,
  FiChevronRight,
  FiGrid,
  FiCopy,
  FiTarget,
  FiXCircle,
  FiSave,
  FiZap,
  FiEdit,
  FiClock,
  FiTrendingUp,
  FiUsers,
  FiHardDrive,
  FiFilter,
  FiArrowRight,
  FiStar,
  FiDatabase,
  FiShield,
  FiChevronUp,
  FiGlobe,
  FiRefreshCw,
  FiX,
  FiMail,
  FiAlertCircle,
  FiTrash2,
  FiBriefcase,
  FiClipboard,
  FiFileText,
  FiLink,
  FiMousePointer,
  FiChevronDown,
} from 'react-icons/fi';

import {
  FaEye,
  FaEyeSlash,
  FaComments,
  FaBullhorn,
  FaChartBar,
  FaCheckCircle,
  FaLayerGroup,
  FaBookmark,
  FaCalendarPlus,
  FaLinkedin,
  FaImage,
  FaCoins,
} from 'react-icons/fa';

import { FcGoogle } from 'react-icons/fc';
import { FilePdfOutlined } from '@ant-design/icons';
import { MailIcon, GlobeIcon } from '@heroicons/react/outline';
import {
  AiOutlinePlus,
  AiFillLinkedin,
  AiOutlineBarChart,
  AiOutlineArrowRight,
  AiOutlineHeart,
  AiOutlineMessage,
  AiOutlineShareAlt,
  AiOutlineEye,
  AiOutlineSearch,
  AiOutlineUser,
  AiOutlineCreditCard,
  AiOutlineRobot,
  AiOutlinePhone,
  AiOutlineCheckCircle,
  AiOutlineCloseCircle,
  AiOutlineStop,
} from 'react-icons/ai';

export const Icons = {
  LogOut: FiLogOut,
  Menu: FiMenu,
  Check: FiCheck,
  Settings: FiSettings,
  Help: FiHelpCircle,
  User: FiUser,
  Message: FiMessageSquare,
  ChevronLeft: FiChevronLeft,
  Grid: FiGrid,
  Save: FiSave,
  Zap: FiZap,
  LogOut: FiLogOut,
  Up: FiChevronUp,
  Down: FiChevronDown,
  FiGlobe: FiGlobe,
  Edit: FiEdit,
  Clock: FiClock,
  Calendar: FiDatabase,
  TrendingUp: FiTrendingUp,
  Mail: FiMail,
  Users: FiUsers,
  HardDrive: FiHardDrive,
  ArrowRight: FiArrowRight,
  Star: FiStar,
  Cross: FiX,
  Shield: FiShield,
  ChevronRight: FiChevronRight,
  Eye: FaEye,
  EyeSlash: FaEyeSlash,
  Google: FcGoogle,
  Comments: FaComments,
  Bullhorn: FaBullhorn,
  ChartBar: FaChartBar,
  CheckCircle: FaCheckCircle,
  LayerGroup: FaLayerGroup,
  Bookmark: FaBookmark,
  CalendarPlus: FaCalendarPlus,
  MailIcon: MailIcon,
  GlobeIcon: GlobeIcon,
  Refresh: FiRefreshCw,
  Plus: AiOutlinePlus,
  Target: FiTarget,
  LinkedIn: AiFillLinkedin,
  BarChart: AiOutlineBarChart,
  Heart: AiOutlineHeart,
  AiMessage: AiOutlineMessage,
  AiRight: AiOutlineArrowRight,
  AiEye: AiOutlineEye,
  AiUser: AiOutlineUser,
  AiSearch: AiOutlineSearch,
  AiRobot: AiOutlineRobot,
  AiCreditCard: AiOutlineCreditCard,
  Share: AiOutlineShareAlt,
  FaLinkedin: FaLinkedin,
  Filter: FiFilter,
  Copy: FiCopy,
  Exclamation: FiXCircle,
  Alert: FiAlertCircle,
  Trash: FiTrash2,
  BriefCase: FiBriefcase,
  Clipboard: FiClipboard,
  Filetext: FiFileText,
  Link: FiLink,
  MousePointer: FiMousePointer,
  Phone: AiOutlinePhone,
  Stop: AiOutlineStop,
  CheckCircle: AiOutlineCheckCircle,
  CloseCircle: AiOutlineCloseCircle,
  PDF: FilePdfOutlined,
  Image: FaImage,
  Credits: FaCoins,
};
