import {
  FiLogOut,
  FiMenu,
  FiSettings,
  FiHelpCircle,
  FiUser,
  FiCheck,
  FiMessageSquare,
  FiChevronLeft,
  FiChevronRight,
  FiGrid,
  FiCopy,
  FiTarget,
  FiXCircle,
  FiSave,
  FiZap,
  FiEdit,
  FiEdit3,
  FiClock,
  FiTrendingUp,
  FiUsers,
  FiHardDrive,
  FiFilter,
  FiArrowRight,
  FiStar,
  FiDatabase,
  FiShield,
  FiChevronUp,
  FiGlobe,
  FiRefreshCw,
  FiX,
  FiMail,
  FiAlertCircle,
  FiTrash2,
  FiBriefcase,
  FiClipboard,
  FiFileText,
  FiLink,
  FiMousePointer,
  FiChevronDown,
  FiTag,
  FiDollarSign,
  FiInfo,
  FiCalendar,
  FiExternalLink,
  FiMessageCircle,
  FiActivity,
  FiLoader,
  FiDownload,
  FiRepeat,
  FiBook,
  FiCode,
  FiSun,
  FiMoon,
  FiEye,
  FiMapPin,
  FiSend,
  FiTrendingDown,
  FiList,
  FiCreditCard,
  FiCommand,
  FiSearch,
} from 'react-icons/fi';

import {
  FaEye,
  FaEyeSlash,
  FaComments,
  FaBullhorn,
  FaChartBar,
  FaCheckCircle,
  FaLayerGroup,
  FaBookmark,
  FaCalendarPlus,
  FaLinkedin,
  FaImage,
  FaCoins,
  FaBuilding,
  FaStickyNote,
  FaRegStickyNote,
  FaHeart,
  FaRegComments,
  FaFlag,
  FaEnvelope,
  FaSearch,
  FaRobot,
  FaHashtag,
} from 'react-icons/fa';

import { FcGoogle } from 'react-icons/fc';
import { FilePdfOutlined } from '@ant-design/icons';
import { MailIcon, GlobeIcon } from '@heroicons/react/outline';
import {
  AiOutlinePlus,
  AiFillLinkedin,
  AiOutlineBarChart,
  AiOutlineArrowRight,
  AiOutlineHeart,
  AiOutlineMessage,
  AiOutlineShareAlt,
  AiOutlineEye,
  AiOutlineSearch,
  AiOutlineUser,
  AiOutlineCreditCard,
  AiOutlineRobot,
  AiOutlinePhone,
  AiOutlineCheckCircle,
  AiOutlineCloseCircle,
  AiOutlineStop,
  AiOutlineCalendar,
  AiOutlineClockCircle,
  AiOutlineBulb,
  AiOutlineExport,
  AiFillRobot,
  AiOutlineMinus,
} from 'react-icons/ai';

import { IoChevronBack, IoChevronForward } from 'react-icons/io5';

export const Icons = {
  Sun: FiSun,
  Map: FiMapPin,
  Moon: FiMoon,
  Document: FiFileText,
  LogOut: FiLogOut,
  Menu: FiMenu,
  Check: FiCheck,
  Code: FiCode,
  Settings: FiSettings,
  Help: FiHelpCircle,
  User: FiUser,
  Message: FiMessageSquare,
  ChevronLeft: FiChevronLeft,
  Grid: FiGrid,
  Save: FiSave,
  Zap: FiZap,
  Up: FiChevronUp,
  Down: FiChevronDown,
  FiGlobe: FiGlobe,
  Edit: FiEdit,
  Edit3: FiEdit3,
  Clock: FiClock,
  Calendar: FiCalendar,
  TrendingUp: FiTrendingUp,
  Mail: FiMail,
  Users: FiUsers,
  HardDrive: FiHardDrive,
  ArrowRight: FiArrowRight,
  Star: FiStar,
  Cross: FiX,
  Shield: FiShield,
  ChevronRight: FiChevronRight,
  Eye: FiEye,
  EyeSlash: FaEyeSlash,
  Google: FcGoogle,
  Comments: FaComments,
  Bullhorn: FaBullhorn,
  ChartBar: FaChartBar,
  CheckCircle: FaCheckCircle,
  LayerGroup: FaLayerGroup,
  Bookmark: FaBookmark,
  CalendarPlus: FaCalendarPlus,
  MailIcon: MailIcon,
  GlobeIcon: GlobeIcon,
  Refresh: FiRefreshCw,
  Plus: AiOutlinePlus,
  Target: FiTarget,
  LinkedIn: AiFillLinkedin,
  BarChart: AiOutlineBarChart,
  Heart: AiOutlineHeart,
  AiMessage: AiOutlineMessage,
  AiRight: AiOutlineArrowRight,
  AiEye: AiOutlineEye,
  AiUser: AiOutlineUser,
  AiSearch: AiOutlineSearch,
  AiRobot: AiOutlineRobot,
  AiCreditCard: AiOutlineCreditCard,
  Share: AiOutlineShareAlt,
  FaLinkedin: FaLinkedin,
  Filter: FiFilter,
  Copy: FiCopy,
  Exclamation: FiXCircle,
  Alert: FiAlertCircle,
  Trash: FiTrash2,
  BriefCase: FiBriefcase,
  Clipboard: FiClipboard,
  Filetext: FiFileText,
  Link: FiLink,
  MousePointer: FiMousePointer,
  Phone: AiOutlinePhone,
  Stop: AiOutlineStop,
  CheckCircle: AiOutlineCheckCircle,
  CloseCircle: AiOutlineCloseCircle,
  PDF: FilePdfOutlined,
  Image: FaImage,
  Credits: FaCoins,
  OutlinedCalendar: AiOutlineCalendar,
  OutlinedCloclCircle: AiOutlineClockCircle,
  BackArrow: IoChevronBack,
  ForwardArrow: IoChevronForward,
  Tag: FiTag,
  Flag: FaFlag,
  Export: AiOutlineExport,
  Building: FaBuilding,
  DollarSign: FiDollarSign,
  Megaphone: FaBullhorn,
  StickyNote: FaStickyNote,
  RegStickyNote: FaRegStickyNote,
  Info: FiInfo,
  MessageCircle: FiMessageCircle,
  Sparkles: AiOutlineBulb,
  Database: FiDatabase,
  Activity: FiActivity,
  Loader: FiLoader,
  ExternalLink: FiExternalLink,
  FaHeart: FaHeart,
  Linkedin: FaLinkedin,
  Envelope: FaEnvelope,
  Search: FiSearch,
  RegComments: FaRegComments,
  Download: FiDownload,
  Repeat: FiRepeat,
  Book: FiBook,
  Robot: AiOutlineRobot,
  Hashtag: FaHashtag,
  Notes: FaRegStickyNote,
  Send: FiSend,
  Files: FiFileText,
  Minus : AiOutlineMinus,
  Gift : FaCoins,
  TrendingDown: FiTrendingDown,
  List: FiList,
  CreditCard: FiCreditCard,
  Command: FiCommand
};
