import { Icons } from './icons';

export const menuItems = [
  {
    to: '/dashboard',
    icon: <Icons.Grid size={18} />,
    label: 'Dashboard',
    activeClass: 'global-sidebar-button-primary  !bg-slate-100',
    hoverClass: 'hover:bg-gray-50 hover:text-black',
    tag: null,
  },
  {
    to: '/dashboard/quick-post',
    icon: <Icons.Zap size={18} />,
    label: 'Quick Post',
    activeClass: 'global-sidebar-button-primary !bg-slate-100',
    hoverClass: 'hover:bg-gray-50 hover:text-black',
    tag: { text: 'MOST USED', color: 'bg-red-500' },
  },
  {
    to: '/dashboard/create-post',
    icon: <Icons.Edit size={18} />,
    label: 'AI Content Creator',
    activeClass: 'global-sidebar-button-primary  !bg-slate-100',
    hoverClass: 'hover:bg-gray-50 hover:text-black',
    tag: { text: 'HOT', color: 'bg-yellow-500' },
  },
  // {
  //   to: '/dashboard/content-calendar',
  //   icon: <Icons.OutlinedCalendar size={18} />,
  //   label: 'Content Calendar',
  //   activeClass: 'global-sidebar-button-primary  !bg-slate-100',
  //   hoverClass: 'hover:bg-gray-50 hover:text-black',
  //   tag: { text: 'NEW', color: 'bg-blue-500' },
  // },
  {
    to: '/dashboard/post-history',
    icon: <Icons.Clock size={18} />,
    label: 'Post History',
    activeClass: 'global-sidebar-button-primary  !bg-slate-100',
    hoverClass: 'hover:bg-gray-50 hover:text-black',
    tag: null,
  },
  {
    to: '/dashboard/saved-leads',
    icon: <Icons.Save size={18} />,
    label: 'Leads',
    activeClass: 'global-sidebar-button-primary  !bg-slate-100',
    hoverClass: 'hover:bg-gray-50 hover:text-black',
    tag: { text: 'NEW', color: 'bg-blue-500' },
  },
  {
    to: '/dashboard/leads-automation',
    icon: <Icons.Robot size={18} />,
    label: 'Automation',
    activeClass: 'global-sidebar-button-primary  !bg-slate-100',
    hoverClass: 'hover:bg-gray-50 hover:text-black',
    tag: { text: 'NEW', color: 'bg-blue-500' },
  },
  {
    to: '/dashboard/email-templates',
    icon: <Icons.Mail size={18} />,
    label: 'Email Templates',
    activeClass: 'global-sidebar-button-primary !bg-slate-100',
    hoverClass: 'hover:bg-gray-50 hover:text-black',
    tag: { text: 'NEW', color: 'bg-blue-500' },
  },
];
